// <auto-generated />
namespace SdojWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-beta1-40122")]
    public sealed partial class CascadeOnDeleteProcess2JudgeCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascadeOnDeleteProcess2JudgeCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201503060148486_CascadeOnDeleteProcess2JudgeCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
